name: FastAPI run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-run:
    runs-on: ubuntu-20.04

    steps:
      # Étape 1 : Récupérer le code source du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2 : Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Étape 3 : Installer les dépendances nécessaires
      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      # Étape 4 : Démarrer le serveur FastAPI
      - name: Start Backend Server
        run: uvicorn main:app --reload &
